Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -48,9 +48,37 @@ jobs:
           IMAGE_TAG: ${{ github.sha }}
         run: |
           echo "Building Docker image..."
-          docker build -f ./code/Dockerfile -t $REGISTRY/$REPOSITORY:$IMAGE_TAG ./code && \
+          docker build -f ./code/Dockerfile -t $REGISTRY/$REPOSITORY:$IMAGE_TAG ./code
+          
           echo "Pushing Docker image to Amazon ECR..."
           docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
+
+      - name: Ensure Docker Image is Available in ECR
+        env:
+          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
+          REPOSITORY: ${{ secrets.ECR_REPOSITORY_NAME }}
+          IMAGE_TAG: ${{ github.sha }}
+        run: |
+          ATTEMPTS=0
+          MAX_ATTEMPTS=10
+          SLEEP_INTERVAL=10  # Wait time in seconds
+          
+          echo "Checking if Docker image is available in ECR..."
+          while [ $ATTEMPTS -lt $MAX_ATTEMPTS ]; do
+            if aws ecr describe-images --repository-name $REPOSITORY --image-ids imageTag=$IMAGE_TAG > /dev/null 2>&1; then
+              echo "Docker image is available in ECR. Proceeding with Lambda deployment."
+              break
+            else
+              echo "Docker image not found. Retrying in $SLEEP_INTERVAL seconds... (Attempt $((ATTEMPTS+1))/$MAX_ATTEMPTS)"
+              ATTEMPTS=$((ATTEMPTS+1))
+              sleep $SLEEP_INTERVAL
+            fi
+          done
+
+          if [ $ATTEMPTS -eq $MAX_ATTEMPTS ]; then
+            echo "Docker image not available in ECR after multiple attempts. Exiting."
+            exit 1
+          fi
 
       - name: Deploy Lambda Function
         env:
